# Generated by Django 4.2.16 on 2024-09-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrimePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_name', models.CharField(max_length=50)),
                ('zh_name', models.CharField(max_length=50)),
                ('platinum1', models.FloatField()),
                ('platinum2', models.FloatField()),
                ('platinum3', models.FloatField()),
                ('platinum_avg', models.FloatField(default=0)),
            ],
        ),
    ]
